src/Entity/Materiels.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\MaterielsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=MaterielsRepository::class)
 * @ORM\Table(name="materiels", indexes={@ORM\Index(columns={"marque", "type", "colisage"}, flags={"fulltext"})})
 */
#[ApiResource]
class Materiels
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $marque;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $type;

    /**
     * @ORM\Column(type="string")
     */
    private $dimension;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $frequence;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PV;

    /**
     * @ORM\OneToOne(targetEntity=Sites::class, inversedBy="materiels", cascade={"persist", "remove"})
     */
    private $affectation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $colisage;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $observations;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $version;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="materiels")
     */
    private $utilisateur;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $calibrated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end_calibrated_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAvaible;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isInVerif;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="materiels")
     */
    private $categorie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDimension(): ?string
    {
        return $this->dimension;
    }

    public function setDimension(string $dimension): self
    {
        $this->dimension = $dimension;

        return $this;
    }

    public function getFrequence(): ?int
    {
        return $this->frequence;
    }

    public function setFrequence(int $frequence): self
    {
        $this->frequence = $frequence;

        return $this;
    }

    public function getPV(): ?string
    {
        return $this->PV;
    }

    public function setPV(?string $PV): self
    {
        $this->PV = $PV;

        return $this;
    }

    public function getAffectation(): ?Sites
    {
        return $this->affectation;
    }

    public function setAffectation(?Sites $affectation): self
    {
        $this->affectation = $affectation;

        return $this;
    }

    public function getColisage(): ?string
    {
        return $this->colisage;
    }

    public function setColisage(?string $colisage): self
    {
        $this->colisage = $colisage;

        return $this;
    }

    public function getObservations(): ?string
    {
        return $this->observations;
    }

    public function setObservations(?string $observations): self
    {
        $this->observations = $observations;

        return $this;
    }

    public function getVersion(): ?int
    {
        return $this->version;
    }

    public function setVersion(?int $version): self
    {
        $this->version = $version;

        return $this;
    }

    public function getUtilisateur(): ?User
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?User $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getCalibratedAt(): ?\DateTime
    {
        return $this->calibrated_at;
    }

    public function setCalibratedAt(?\DateTime $calibrated_at): self
    {
        $this->calibrated_at = $calibrated_at;

        return $this;
    }

    public function getEndCalibratedAt(): ?\DateTime
    {
        return $this->end_calibrated_at;
    }

    public function setEndCalibratedAt(?\DateTime $end_calibrated_at): self
    {
        $this->end_calibrated_at = $end_calibrated_at;

        return $this;
    }

    public function getIsAvaible(): ?bool
    {
        return $this->isAvaible;
    }

    public function setIsAvaible(bool $isAvaible): self
    {
        $this->isAvaible = $isAvaible;

        return $this;
    }

    public function getIsInVerif(): ?bool
    {
        return $this->isInVerif;
    }

    public function setIsInVerif(bool $isInVerif): self
    {
        $this->isInVerif = $isInVerif;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Controller/Materiel/MaterielController.php
<?php

namespace App\Controller\Materiel;

use App\Entity\Materiels;
use App\Form\MaterielFormType;
use App\Form\SearchMaterielType;
use App\Repository\MaterielsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MaterielController extends AbstractController
{

    private $repoMateriels;

    function __construct( MaterielsRepository $repoMateriels )
    {
        $this->repoMateriels = $repoMateriels;
    }

    //! READ_ALL 
    // Route principal affichant tous les produits pour le magasinier (action visible)
    #[Route('/materiels', name: 'app_materiels_index')]
    public function index(PaginatorInterface $paginator, Request $request, MaterielsRepository $repoMateriels): Response
    {
        //? Mise en place de la pagination
        $data = $this->repoMateriels->findAll();

        $materiels = $paginator->paginate(
            $data, 
            $request->query->getInt('page', 1), 
            20
        );

        // Executer une recherche par mot clé
        $form = $this->createForm(SearchMaterielType::class);
        $search = $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $materiels = $repoMateriels->search(
                $search->get('mots')->getData(),
                $search->get('categorie')->getData()
            );
        }
        
        // dd($materiels);

        return $this->render('materiels/index.html.twig', [
            'materiels' => $materiels,
            'form' => $form->createView()
        ]);
    }

    //!TESTS ONLY
    #[Route('/materiels/test', name: 'app_materiels_test')]
    #[IsGranted('ROLE_MAGASINIER')]
    public function pageTest(Request $request, MaterielsRepository $repoMateriels): Response
    {
        $materiels = $this->repoMateriels->findAll();

        // Executer une recherche par mot clé
        $form = $this->createForm(SearchMaterielType::class);
        $search = $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $materiels = $repoMateriels->search(
                $search->get('mots')->getData(),
                $search->get('categorie')->getData()
            );
        }
        

        return $this->render('materiels/search.html.twig', [
            'materiels' => $materiels,
            'form' => $form->createView(),
        ]);
    }

    //! READ_ONE 
    // Route détaillant un produit
    #[Route('/materiels/{id<[0-9]+>}', methods: 'GET', name: 'app_materiel_show')]
    #[IsGranted('ROLE_USER')]
    public function show(Materiels $materiel): Response
    {
        return $this->render('materiels/show.html.twig', compact('materiel'));
    
    }

    //! CREATE 
    // Ajout d'un nouveau matériel
    #[Route('/materiels/create', methods:['GET', 'POST'], name:'app_materiels_create')]
    #[IsGranted('ROLE_MAGASINIER')]
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        $materiel = new Materiels();

        $form = $this->createForm(MaterielFormType::class, $materiel);
        
        $form->handleRequest($request);

        if ($form -> isSubmitted() && $form->isValid()) {
            
            $em->persist($materiel);
            $em->flush();

            $this->addFlash('success', 'Matériel crée avec succès : ');

            return $this->redirectToRoute('app_materiel_show', ['id' => $materiel->getId()]);
        }

        return $this->renderForm('materiels/create.html.twig', [
            'form' => $form
        ]);
    }

    //! UPDATE
    // Modification ou mise à jour d'un produit
    #[Route('/materiels/{id<[0-9]+>}/edit', methods:['GET', 'POST'], name:'app_materiels_edit')]
    #[IsGranted('ROLE_MAGASINIER')]
    public function edit(Materiels $materiel, Request $request, EntityManagerInterface $em): Response 
    {
        
        $form = $this->createForm(MaterielFormType::class, $materiel);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            $this->addFlash('success', 'Modification sauvegardé');

            return $this->redirectToRoute('app_materiel_show', ['id' => $materiel->getId()]);
        }

        return $this->renderForm('materiels/edit.html.twig', [
            'materiel' => $materiel, 
            'form' => $form
        ]);
    }

    //! DELETE
    // Effacer un matériel de la base de donnée
    #[Route('/materiels/{id<[0-9]+>}/delete', methods:'POST', name:'app_materiels_delete')]
    #[IsGranted('ROLE_MAGASINIER')]
    public function delete(Request $request, Materiels $materiel, EntityManagerInterface $em): Response
    {
        if ($this->isCsrfTokenValid('materiel_deletion_' . $materiel->getId(), $request->request->get('csrf_token')) ) {
            $em->remove($materiel);
            $em->flush();

            $this->addFlash('danger', 'Matériel '.$materiel->getMarque(). ' ' .$materiel->getType() .'a été supprimé !');
        } 
            return $this->redirectToRoute('app_materiels_index');

    }


}

templates/materiels/_form.html.twig
{{form_start(form)}}
			

    <div class="row mb-4 mt-3">
        <div id="marque" class="col-sm-12 col-md-4 col-12">
            {{ form_row(form.marque) }}
        </div>

        <div id="type" class="col-sm-12 col-md-4 col-12">
            {{ form_row(form.type) }}
        </div>

        <div id="reference" class="col-sm-12 col-md-4 col-12">
            {{ form_row(form.reference) }}
        </div>
    </div>

    <div id="dimension" class="row">
        <div class="col-sm-12 col-md-4 col-12">
            {{ form_row(form.dimension) }}
        </div>

        <div id="frequence" class="col-sm-12 col-md-4 col-12">
            {{ form_row(form.frequence) }}
        </div>

        <div id="quantity" class="col-sm-12 col-md-4 col-12">
            {{ form_row(form.quantity) }}
        </div>
    </div>

    <div id="observations" class="row">
        <div class="col-sm-12 col-md-4 col-12">
            {{ form_row(form.observations)}}
        </div>

        <div id="colisage" class="col-sm-12 col-md-4 col-12">
            {{ form_row(form.colisage)}}
        </div>

        {# <div id="affectation" class="col-sm-12 col-md-4 col-12">
            {{ form_row(form.affectation)}}
        </div> #}
    </div>

    <hr>

    <div id="estDisponible" class="row">
        <div class="fw-bold text-success col-sm-12 col-md-6 col-12">
            {{ form_row(form.isAvaible) }}
        </div>
        <div id="estEnVerif" class="fw-bold text-danger col-sm-12 col-md-6 col-12">
            {{ form_row(form.isInVerif) }}
        </div>
    </div>

    <div class="row my-5  border border-dark rounded shadow p-3 h6 bg-light text-underline">
        <div class="col-sm-12 col-md-6 col-12">
            {{ form_row(form.calibrated_at) }}
        </div>
        <div class="col-sm-12 col-md-6 col-12">
            {{ form_row(form.end_calibrated_at) }}
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-6 col-12">
            {{ form_row(form.pv)}}
        </div>
        <div class="col-sm-12 col-md-6 col-12">
            {{ form_row(form.categorie) }}
    </div>

    <div class="d-flex justify-content-between">	
        <button type="submit" class="btn btn-outline-success w-50 mb-5 me-1">
            {{ submitButtonText ?? 'Ajouter le materiel' }}
        </button>
         <a href="{{path('app_materiels_index')}}" class="btn btn-outline-danger w-50 mb-5 ms-1">Annuler</a>
    </div>

{{form_end(form)}}

templates/materiels/_pagination.html.twig
{% if pageCount > 1 %}
    <nav>
        {% set classAlign = (align is not defined) ? '' : align=='center' ? ' justify-content-center' : (align=='right' ? ' justify-content-end' : '') %}
        {% set classSize = (size is not defined) ? '' : size=='large' ? ' pagination-lg' : (size=='small' ? ' pagination-sm' : '') %}
        <ul class="pagination{{ classAlign }}{{ classSize }}">

            {% if previous is defined %}
                <li class="page-item">
                    <a class="page-link" rel="prev" href="{{ path(route, query|merge({(pageParameterName): previous})) }}">&laquo;&nbsp;{{ 'label_previous'|trans({}, 'KnpPaginatorBundle') }}</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo;&nbsp;{{ 'label_previous'|trans({}, 'KnpPaginatorBundle') }}</span>
                </li>
            {% endif %}

            {% if startPage > 1 %}
                <li class="page-item">
                    <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 1})) }}">1</a>
                </li>
                {% if startPage == 3 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 2})) }}">2</a>
                    </li>
                {% elseif startPage != 2 %}
                    <li class="page-item disabled">
                        <span class="page-link">&hellip;</span>
                    </li>
                {% endif %}
            {% endif %}

            {% for page in pagesInRange %}
                {% if page != current %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): page})) }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="page-item active">
                        <span class="page-link">{{ page }}</span>
                    </li>
                {% endif %}

            {% endfor %}

            {% if pageCount > endPage %}
                {% if pageCount > (endPage + 1) %}
                    {% if pageCount > (endPage + 2) %}
                        <li class="page-item disabled">
                            <span class="page-link">&hellip;</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): (pageCount - 1)})) }}">{{ pageCount -1 }}</a>
                        </li>
                    {% endif %}
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): pageCount})) }}">{{ pageCount }}</a>
                </li>
            {% endif %}

            {% if next is defined %}
                <li class="page-item">
                    <a class="page-link" rel="next" href="{{ path(route, query|merge({(pageParameterName): next})) }}">{{ 'label_next'|trans({}, 'KnpPaginatorBundle') }}&nbsp;&raquo;</a>
                </li>
            {% else %}
                <li  class="page-item disabled">
                    <span class="page-link">{{ 'label_next'|trans({}, 'KnpPaginatorBundle') }}&nbsp;&raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/materiels/create.html.twig
{% extends "layouts/base.html.twig" %}

{% block title 'Ajouter un materiel' %}

{% block body %}
    <section id="creation-materiel">
        <div class="mt-5 row">
            <div class="col-md-6 mx-auto">
                <div class="shadow-lg jumbotron text-center mt-2 p-2 rounded col-11" id="title">
                    <h1 class="shadow-4"> Ajouter un nouveau materiel </h1>
                </div>
                {% include ('materiels/_form.html.twig') %}
            </div>
        </div>
    </section>
{% endblock %}

templates/materiels/edit.html.twig
{% extends "layouts/base.html.twig" %}

{% block body %}


	<section class="container" id="edition-materiel">
		<div class="row">
			<div class="shadow-lg jumbotron text-center mt-2 p-2 rounded col-11" id="title">
				<h1 class="shadow-4">
					{{ materiel.marque }}
				</h1>
			</div>
			<div class="mt-2 col-1">
				<a href="{{path('app_materiels_index')}}" class="btn btn-outline-primary _perso-primary btn-floating float-end rounded-circle">
					<i class="fas fa-th-list"></i>
				</a>
			</div>
		</div>

		{# Inclure mon formulaire et passer une variable pour afficher le nom correct du bouton #}
		{{ include ('materiels/_form.html.twig', { submitButtonText: 'Enregistrer les modifications' }) }}

	</section>

{% endblock %}

templates/materiels/index.html.twig
{% extends "layouts/base.html.twig" %}

{% block title  parent() ~ ' | Magasinier'  %}

{% block body %}

	{% if (app.user.isAutorised == false) %}
		<div style="z-index: 999999999;" class="mt-5 container alert alert-danger shadow" style="height:10rem; position: fixed; top:50%; left:50%; transform: translate(-50%, -50%);">
			<p class="lead text-center mt-5" style:"position:absolute; top:auto">Vous n'êtes pas encore autoiser à accèder à l'application. Soyez patient, un administrateur va prochainement vous autoriser.</p>
		</div>
	{% else %}

    {#* Formulaire de recherche *#}


	<table class="container table mt-3">
		<thead class="text-center h6">
			<tr>
				<th scope="col">#</th>
				<th scope="col">Reférence</th>
				<th scope="col">Marque</th>
				<th scope="col">Type</th>
				<th scope="col">Dimension</th>
				<th scope="col">F</th>
				<th scope="col">PV</th>
				<th scope="col">Affectation</th>
				<th scope="col">Catégorie</th>
				<th scope="col">Observations</th>
				<th class="text-center" scope="col" colspan="2">Action</th>
			</tr>
		</thead>

		{% for materiel in materiels %}

			<tbody>
				<tr class="text-center">
					<th scope="row">
						{{ "%03d"|format(materiel.id) }}
					</th>
					<td>
						{{ materiel.reference }}
					</td>
					<td>
						{{ materiel.marque }}
					</td>
					<td>
						{{ materiel.type }}
					</td>
					<td>
						{{ materiel.dimension }}
					</td>
					<td>
						{{ materiel.frequence }}
					</td>
					<td>
						{{ materiel.pv }}
					</td>
					<td>
						{{ materiel.colisage }}
					</td>
					<td>
						{{ materiel.categorie|capitalize }}
					</td>
					<td>
						{{ materiel.Observations|u.truncate(10, '...', false) }}
					</td>
					<td>
						<a class="btn btn-sm btn-success" href="{{ path('app_materiel_show', {'id': materiel.id}) }}">Consulter la fiche</a>
					</td>
					<td>
						{% if is_granted ("ROLE_MAGASINIER") %}
							<a class="btn btn-sm btn-warning me-1" href="{{ path('app_materiels_edit', {'id': materiel.id}) }}">Modifier</a>
							<a  class="btn btn-sm btn-danger ms-1" href="#"
								onclick="event.preventDefault();
								confirm('Êtes-vous sûr de vouloir supprimer?') && 
								document.getElementById('materiel-deletion-form-{{materiel.id}}').submit();">
								Effacer
							</a> 
							<form id="materiel-deletion-form-{{materiel.id}}" style="display:" action="{{ path('app_materiels_delete', {'id': materiel.id}) }}" method="POST">
								<input type="hidden" name="csrf_token" value="{{ csrf_token('materiel_deletion_' ~ materiel.id) }}">
							</form>
						{% endif %}
					</td>
					
				</tr>
			</tbody>
		{% endfor %}
	</table>
	{#* Pagination *#}

	<div class="d-flex justify-content-center">
		{% do materiels.setPageRange(5) %}
		{{ knp_pagination_render(materiels, 'materiels/_pagination.html.twig') }}
	</div>   


	{% endif %}
{% endblock %}

templates/materiels/search.html.twig
{% extends 'layouts/base.html.twig' %}

{% block body %}


{#* Formulaire de recherche *#}
<section id="recherche-materiel">
    <div class="container">
        <div class="mt-2 mb-4 h-100 p-4 text-white perso_bg_dark rounded-3">
            {{form_start(form)}}
            <div class="form-row">
                <div class="col">
                    {{ form(form) }}
                </div>
            </div>
            {{form_end(form)}}
        </div> 
    </div>
</section>

<section class="container mb-5" id="materiel-carte">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for materiel in materiels %}
            <div class="col">
                <div class="card h-100 shadow">

                    <img src="https://source.unsplash.com/1600x900/?php,Technology,Industries.jpg" class="card-img-top img-fluid" alt="..."/>

                    <div class="card-body">
                        <h5 class="card-title fw-bold">{{materiel.reference}} | {{materiel.categorie|capitalize}}</h5>
                        <p class="card-text"> {{materiel.marque}} {{materiel.type}} </p>
                        <div class="d-flex justify-content-between">
                        <p class="card-text"> {{materiel.dimension}} mm | {{materiel.frequence}} mHz</p>
                            {% if materiel.isAvaible %}
                                ✅
                            {% else %}
                                ❌
                            {% endif %}
                        </div>
                        <p class="card-text"> {{materiel.observations}}</p>
                    </div>
                    <div>
                        <a class="d-block mx-auto btn btn-outline-success w-50 mb-2" href="{{path('app_materiel_show', {'id': materiel.id})}}">Consulter la fiche</a>
                    </div>

                    <div class="card-footer">
                        <small class="text-muted">Fin de validité: </small>
                        <span class="text-danger">{{materiel.endCalibratedAt|date('d/m/Y')}}</span>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
</section>

{% endblock %}

templates/materiels/show.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title materiel.marque ~ ' ' ~ materiel.type %}

{% block body %}


	<div class="mt-5">
		<h1 class="text-center">{{materiel.reference}}
			<span class="perso_badge py-1 px-2 align-middle">{{materiel.id}}</span>
		</h1>
		<h5 class="shadow w-25 mx-auto bg-info text-center py-1 mb-5 fw-light">{{materiel.categorie|capitalize}}</h5>
	</div>

	<div class="col-md-6 mx-auto">
		<div class="mx-auto card shadow mb-5" style="width:35rem; height:auto;">
			<img src="https://source.unsplash.com/1600x900/?inspection,php" class="card-img-top img-fluid" alt="{{materiel.reference}}" height="250">
			<div class="card-body">

				<div class="row">
					<div class="col-8">
						<h1 class="h4 card-title">
							{{materiel.marque}}
							{{materiel.type}}
							<span class="text-muted h6">
								({{materiel.reference}})
							</span>
						</h1>
					</div>
					<div class="col-4">
						<span class="text-muted float-end">
							{{materiel.dimension}}
							-
							{{materiel.frequence}}
							Mhz</span>
					</div>
				</div>

				<div class="row">
					<div class="container h5 d-flex justify-content-between">
						<span class="py-1 rounded text-center bg-success text-white fw-light h6 w-50 me-1">{{materiel.calibratedAt|date('d/m/Y')}}</span>
						<span class="py-1 rounded text-center bg-danger  text-white fw-light h6 w-50 ms-1">{{materiel.endCalibratedAt|date('d/m/Y')}}</span>
					</div>
				</div>

				<div class="row">
					<div class="col-12">
						{% if materiel.isAvaible %}
							<div class="card-text alert alert-success">
								<p class="lead">Cet article est disponible.</p>
							</div>
						{% else %}
							<div class="card-text alert alert-danger">
								<p class="lead">Cet article n'est pas disponible, il est actuellement affecté sur le site de
									{{materiel.colisage}}.</p>
							</div>
						{% endif %}
					</div>
				</div>

				<div class="card-footer text-muted h6 text-center mt-2">
					<p>Ici sera affiché un décompte de jour restant jusqu'au prochain étalonnage</p>
				</div>

				<div class="row">
					{% if is_granted ("ROLE_MAGASINIER") %}
						<div class="d-flex justify-content-between">
							<a class="btn btn-sm btn-warning w-50 me-1" href="{{ path('app_materiels_edit', {'id': materiel.id}) }}">Modifier</a>
							<a class="btn btn-sm btn-danger w-50 ms-1" href="#" onclick="event.preventDefault();
																																				confirm('Êtes-vous sûr de vouloir supprimer?') &&
																																				document.getElementById('materiel-deletion-form').submit();">
								Effacer
							</a>

							<form id="materiel-deletion-form" style="display:none" action="{{ path('app_materiels_delete', {'id': materiel.id}) }}" method="POST">
								<input type="hidden" name="csrf_token" value="{{ csrf_token('materiel_deletion_' ~ materiel.id) }}">
								<button type="submit">Effacer</button>
							</form>
						</div>
					{% endif %}
				</div>
			</div>

		{% endblock %}